name: AI Code Repair

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  codeql-analysis:
    name: Analyze code with CodeQL
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Initialize CodeQL
      uses: github/codeql-action/init@v2
      with:
        languages: 'javascript,python'  # 指定要分析的语言

    - name: Perform CodeQL Analysis
      uses: github/codeql-action/analyze@v2

    - name: Install Python
      uses: actions/setup-python@v2
      with:
        python-version: "3.10"  # 指定Python版本

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt  # 从 requirements.txt 文件安装依赖
        pip install pytest  # 单独安装 pytest 确保它可用

    - name: Run Tests
      run: |
        pytest --benchmark-json output.json benches/
