name: Code coverage

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./safetensors

    steps:
      - uses: actions/checkout@v3

      - name: Install Rust Stable
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          components: llvm-tools-preview
          override: true

      - uses: Swatinem/rust-cache@v2

      - name: Install cargo-llvm-cov for Ubuntu
        run: cargo install cargo-llvm-cov

      - name: Coverage report
        run: cargo llvm-cov --release --lcov --output-path lcov.info

      - name: Upload to codecov.io
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }} # 在 GitHub Secrets 中设置你的 token
          files: ./safetensors/lcov.info # 确保这里是正确的 lcov 文件路径
          fail_ci_if_error: true
          verbose: true
