name: Simple benchmarks
on:
  push:
    branches:
      - main

permissions:
  deployments: write
  contents: write

jobs:
  benchmark:
    name: Performance regression check
    runs-on: ubuntu-latest
    steps:
      # Checkout code
      - uses: actions/checkout@v3

      # Install Rust
      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          components: rustfmt, clippy

      # Install Python
      - name: Install Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.10"
          architecture: "x64"

      # Install dependencies
      - name: Install Dependencies
        working-directory: ./bindings/python
        run: |
          # Upgrade pip
          python -m pip install --upgrade pip
          # 强制降级 NumPy 版本以确保兼容性
          pip install "numpy<2"
          # 安装 TensorFlow CPU-only 版本，避免 CUDA 问题
          pip install tensorflow-cpu==2.10.0
          # 安装其他依赖项
          if [ -f "requirements.txt" ]; then
            pip install -r requirements.txt
          else
            echo "requirements.txt not found, skipping dependency installation."
          fi

      # Run tests using Rust and Python
      - name: Run tests
        working-directory: ./bindings/python
        run: |
          cargo test
          pytest --benchmark-json output.json benches/
      
      # Download previous benchmark data from cache if exists
      - name: Download previous benchmark data
        uses: actions/cache@v1
        with:
          path: ./cache
          key: ${{ runner.os }}-benchmark

      # Store benchmark result
      - name: Store benchmark result
        uses: benchmark-action/github-action-benchmark@v1
        with:
          tool: 'pytest'
          output-file-path: ./bindings/python/output.json
          github-token: ${{ secrets.GITHUB_TOKEN }}
          auto-push: true
          comment-on-alert: true
          alert-comment-cc-users: '@Narsil'
