import os
import subprocess

# Define the path to the requirements file
requirements_file = "requirements.txt"

# Check if the requirements.txt file exists
if os.path.exists(requirements_file):
    print(f"'{requirements_file}' found, proceeding with installation...")
    try:
        # Install the requirements using subprocess to run shell command
        result = subprocess.run(
            ["pip", "install", "-r", requirements_file],
            check=True,
            text=True,
            capture_output=True
        )
        print("Requirements installed successfully:")
        print(result.stdout)
    except subprocess.CalledProcessError as e:
        print(f"An error occurred while installing the requirements: {e.stderr}")
else:
    print(f"Error: '{requirements_file}' not found in the current directory. Please make sure the file exists.")

